<?php

namespace Database\Seeders;

use Carbon\Carbon;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $city = [
            ['id' => '1',  'name'=>'Karachi', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '2',  'name'=>'Lahore', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '3',  'name'=>'Faisalabad', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '4',  'name'=>'Rawalpindi', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '5',  'name'=>'Gujranwala', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '6',  'name'=>'Peshawar', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '7',  'name'=>'Multan', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '8',  'name'=>'Saidu Sharif', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '9',  'name'=>'Hyderabad City', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '10',  'name'=>'Islamabad', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '11',  'name'=>'Quetta', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '12',  'name'=>'Bahawalpur', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '13',  'name'=>'Sargodha', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '14',  'name'=>'Sialkot City', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '15',  'name'=>'Sukkur', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '16',  'name'=>'Larkana', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '17',  'name'=>'Chiniot', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '18',  'name'=>'Shekhupura', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '19',  'name'=>'Jhang City', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '20',  'name'=>'Dera Ghazi Khan', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '21',  'name'=>'Gujrat', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '22',  'name'=>'Rahimyar Khan', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '23',  'name'=>'Kasur', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '24',  'name'=>'Mardan', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '25',  'name'=>'Mingaora', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '26',  'name'=>'Nawabshah', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '27',  'name'=>'Sahiwal', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '28',  'name'=>'Mirpur Khas', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '29',  'name'=>'Okara', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '30',  'name'=>'Mandi Burewala', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '31',  'name'=>'Jacobabad', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '32',  'name'=>'Saddiqabad', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '33',  'name'=>'Kohat', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '34',  'name'=>'Muridke', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '35',  'name'=>'Muzaffargarh', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '36',  'name'=>'Khanpur', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '37',  'name'=>'Gojra', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '38',  'name'=>'Mandi Bahauddin', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '39',  'name'=>'Abbottabad', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '40',  'name'=>'Turbat', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '41',  'name'=>'Dadu', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '42',  'name'=>'Bahawalnagar', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '43',  'name'=>'Khuzdar', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '44',  'name'=>'Pakpattan', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '45',  'name'=>'Tando Allahyar', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '46',  'name'=>'Ahmadpur East', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '47',  'name'=>'Vihari', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '48',  'name'=>'Jaranwala', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '49',  'name'=>'New Mirpur', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '50',  'name'=>'Kamalia', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '51',  'name'=>'Kot Addu', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '52',  'name'=>'Nowshera', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '53',  'name'=>'Swabi', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '54',  'name'=>'Khushab', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '55',  'name'=>'Dera Ismail Khan', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '56',  'name'=>'Chaman', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '57',  'name'=>'Charsadda', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '58',  'name'=>'Kandhkot', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '59',  'name'=>'Chishtian', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '60',  'name'=>'Hasilpur', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '61',  'name'=>'Attock Khurd', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '62',  'name'=>'Muzaffarabad', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '63',  'name'=>'Mianwali', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '64',  'name'=>'Jalalpur Jattan', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '65',  'name'=>'Bhakkar', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '66',  'name'=>'Zhob', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '67',  'name'=>'Dipalpur', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '68',  'name'=>'Kharian', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '69',  'name'=>'Mian Channun', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '70',  'name'=>'Bhalwal', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '71',  'name'=>'Jamshoro', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '72',  'name'=>'Pattoki', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '73',  'name'=>'Harunabad', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '74',  'name'=>'Kahror Pakka', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '75',  'name'=>'Toba Tek Singh', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '76',  'name'=>'Samundri', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '77',  'name'=>'Shakargarh', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '78',  'name'=>'Sambrial', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '79',  'name'=>'Shujaabad', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '80',  'name'=>'Hujra Shah Muqim', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '81',  'name'=>'Kabirwala', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '82',  'name'=>'Mansehra', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '83',  'name'=>'Lala Musa', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '84',  'name'=>'Chunian', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '85',  'name'=>'Nankana Sahib', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '86',  'name'=>'Bannu', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '87',  'name'=>'Pasrur', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '88',  'name'=>'Timargara', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '89',  'name'=>'Parachinar', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '90',  'name'=>'Chenab Nagar', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '91',  'name'=>'Gwadar', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '92',  'name'=>'Abdul Hakim', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '93',  'name'=>'Hassan Abdal', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '94',  'name'=>'Tank', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '95',  'name'=>'Hangu', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '96',  'name'=>'Risalpur Cantonment', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '97',  'name'=>'Karak', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '98',  'name'=>'Kundian', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '99',  'name'=>'Umarkot', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '100', 'name'=> 'Chitral', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '101', 'name'=> 'Dainyor', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '102', 'name'=> 'Kulachi', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '103', 'name'=> 'Kalat', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '104', 'name'=> 'Kotli', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '105', 'name'=> 'Gilgit', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '106', 'name'=> 'Narowal', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '107', 'name'=> 'Khairpur Mir’s', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '108', 'name'=> 'Khanewal', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '109', 'name'=> 'Jhelum', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '110', 'name'=> 'Haripur', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '111', 'name'=> 'Shikarpur', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '112', 'name'=> 'Rawala Kot', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '113', 'name'=> 'Hafizabad', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '114', 'name'=> 'Lodhran', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '115', 'name'=> 'Malakand', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '116', 'name'=> 'Attock City', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '117', 'name'=> 'Batgram', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '118', 'name'=> 'Matiari', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '119', 'name'=> 'Ghotki', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '120', 'name'=> 'Naushahro Firoz', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '121', 'name'=> 'Alpurai', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '122', 'name'=> 'Bagh', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '123', 'name'=> 'Daggar', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '124', 'name'=> 'Leiah', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '125', 'name'=> 'Tando Muhammad Khan', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '126', 'name'=> 'Chakwal', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '127', 'name'=> 'Badin', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '128', 'name'=> 'Lakki', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '129', 'name'=> 'Rajanpur', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '130', 'name'=> 'Dera Allahyar', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '131', 'name'=> 'Shahdad Kot', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '132', 'name'=> 'Pishin', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '133', 'name'=> 'Sanghar', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '134', 'name'=> 'Upper Dir', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '135', 'name'=> 'Thatta', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '136', 'name'=> 'Dera Murad Jamali', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '137', 'name'=> 'Kohlu', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '138', 'name'=> 'Mastung', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '139', 'name'=> 'Dasu', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '140', 'name'=> 'Athmuqam', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '141', 'name'=> 'Loralai', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '142', 'name'=> 'Barkhan', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '143', 'name'=> 'Musa Khel Bazar', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '144', 'name'=> 'Ziarat', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '145', 'name'=> 'Gandava', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '146', 'name'=> 'Sibi', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '147', 'name'=> 'Dera Bugti', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '148', 'name'=> 'Eidgah', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '149', 'name'=> 'Uthal', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '150', 'name'=> 'Wah Cantt', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '151', 'name'=> 'Chilas','created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '152', 'name'=> 'Panjgur', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '153', 'name'=> 'Gakuch', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '154', 'name'=> 'Qila Saiful lah', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '155', 'name'=> 'Kharan', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '156', 'name'=> 'Aliabad', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '157', 'name'=> 'Awaran', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],
            ['id' => '158', 'name'=> 'Dalbandin', 'created_at' => Carbon::now()->format('Y-m-d H:i:s')],

        ];
        DB::table('cities')->insert($city);
    }
}
